- name: install docker
  become: yes
  shell:
    cmd: curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh && rm get-docker.sh
    chdir: /tmp
    creates: /usr/bin/docker
    warn: false

- name: install docker compose
  become: yes
  shell:
    cmd: sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose
    chdir: /tmp
    creates: /usr/local/bin/docker-compose
    warn: false