- name: install docker
  become: yes
  shell:
    cmd: curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh && rm get-docker.sh
    chdir: /tmp
    creates: /usr/bin/docker
    warn: false
    
- name: install docker compose plugin
  become: yes
  shell:
    cmd: COMPOSE_LATEST_VERSION=$(curl -sL https://api.github.com/repos/docker/compose/releases/latest | grep '"tag_name":' | cut -d'"' -f4) && mkdir -p /usr/lib/docker/cli-plugins/ && curl -SL https://github.com/docker/compose/releases/download/$COMPOSE_LATEST_VERSION/docker-compose-linux-x86_64 -o /usr/lib/docker/cli-plugins/docker-compose && chmod +x /usr/lib/docker/cli-plugins/docker-compose
    chdir: /tmp
    creates: /usr/lib/docker/cli-plugins/docker-compose
    warn: false
